// <auto-generated />
namespace DB_Logic.Migrations.Local
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialLocalDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialLocalDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201612170935296_InitialLocalDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
